# Generated by Django 3.1.3 on 2021-06-15 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs')], max_length=48)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(default='F', max_length=1)),
                ('educational_qualification', models.CharField(max_length=64)),
                ('professional_details', models.CharField(max_length=82)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('tutor_id', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, max_length=23)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(default='F', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('subscribed_to', models.CharField(choices=[('Spela-studio', 'Seeds'), ('Spela-Smart', 'Sprouts'), ('Spela-first', 'Blooms')], max_length=30)),
                ('gaurdian_name', models.CharField(max_length=64)),
                ('gaurdian_phone_no', models.CharField(max_length=11, unique=True)),
                ('registered_email', models.EmailField(blank=True, max_length=254)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('day_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(max_length=10, null=True)),
                ('gst', models.CharField(max_length=21, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=15, null=True)),
                ('communication_address', models.CharField(blank=True, max_length=15, null=True)),
                ('job', models.CharField(blank=True, max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, max_length=24, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('martial_status', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], max_length=15)),
                ('educational_qualification', models.CharField(choices=[('Doctorate', 'Doctorate'), ('Post-Graduate', 'Post-Graduate'), ('Graduate', 'Graduate'), ('Intermediate', 'Intermediate'), ('Matric', 'Matric'), ('None', 'None')], max_length=64)),
                ('professional_details', models.CharField(choices=[('Business', 'Business'), ('Self Employed', 'Self Employed'), ('Professional', 'Profess2ional'), ('Govt_services', 'Govt_services'), ('Pvt_services', 'Pvt-services')], max_length=82)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
