# Generated by Django 3.1.3 on 2021-06-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='dob',
        ),
    ]
