# Generated by Django 3.1.3 on 2021-06-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_teacher_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='franschise_model',
            field=models.CharField(choices=[('Spela-studio', 'Studio'), ('Spela-Smart', 'Smart'), ('Spela-first', 'First')], default='studio', max_length=22),
        ),
    ]
