# Generated by Django 3.1.3 on 2021-06-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='address_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='postcode',
            field=models.IntegerField(default='122001'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
