# Generated by Django 3.1.3 on 2021-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(max_length=20),
        ),
    ]
